spring.application.name=backend

server.port=${PORT:8082}

spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=${MONGODB_DATABASE:janseva}

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

spring.jackson.serialization.fail-on-empty-beans=false

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always