spring.application.name=backend

server.port=8082

spring.data.mongodb.uri=mongodb://localhost:27017/janseva

spring.data.mongodb.database=janseva

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

logging.level.org.springframework.security=DEBUG
spring.jackson.serialization.fail-on-empty-beans=false

management.endpoints.web.exposure.include=*

management.endpoint.health.show-details=always